### ISSUE TITLE
Fixes and enhancements in the header part

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Buerokratt-Chatbot#721]
AS A Bürokratt User
I WANT to only receive sound and popup notifications when a new message is received
SO THAT I would know when a new message is received

currently whenever a user switches modules, a popup and ding is played for each unanswered chat.
a ding and popup is also played seemingly in 2 minute intervals.

I WANT the backoffice user status to not change randomly
SO THAT I can reliably keep my status as ACTIVE

currently it seems that there are 2 separate parameters that control the active status. one of them is a boolean 'active' and the other one is a string 'status'.

### Acceptance Criteria
- [ ] Notification popup and ding is only played when a new message is received
- [x] Backoffice user active status does not change randomly and only changes when switched or a time limit is reached
- [ ] Bowser notifications are working. Sound and pop-up messages are working.

**Comment by 1AhmedYasser** [comment]
Related to https://github.com/buerokratt/Buerokratt-Chatbot/issues/682

**Comment by jaX10bt** [comment]
[BUG]

Upon first logging in to the backoffice, both 'active' and 'status' are set to 'false' and 'offline' respectively.
When the user then presses 'Kohal/Eemal', the POST request changes the users status in the back end but this information is not updated in the front end until another GET request is sent by for example navigating to another module.

https://github.com/buerokratt/Buerokratt-Chatbot/assets/132996313/5cb2b655-2747-4ed0-b439-846dee4bc7c3

**Comment by jaX10bt** [comment]
The new message notification 'ding' sound is only played in the backoffice when the backoffice tab is active. When the backoffice tab is not active (even when it is visible), there is no indication of a forwarded chat.

![Image](https://github.com/user-attachments/assets/915970eb-0b1b-42e6-90a4-7979fd0b11e4)

**Comment by jaX10bt** [comment]
[BUG]

In training module, the popup modal that is supposed to ask 'Kas soovid muuta staatuseks "kohal"?' displays 'global.statusChangeQuestion'


![Image](https://github.com/user-attachments/assets/0db51dcf-ef63-4d9b-821e-209db0c072c8)

**Comment by turnerrainer** [comment]
Header package needs to be deployed to NPM first.

**Comment by joonasroosalung** [comment]
v0.1.11 published on 8th of august https://www.npmjs.com/package/@buerokratt-ria/header/v/0.1.11

**Comment by jaX10bt** [comment]
Popup notifications and sound notifications are not working properly. 

Active chats request is only sent when the tab is active. When the backoffice window is not active or minimized, there is no indication of a new chat.

![image](https://github.com/user-attachments/assets/b1644412-c77a-4288-a86b-acaf75d2ac08)

**Comment by SanderSepp** [comment]
When admin sent message and user reads it, message with message-read event was inserted to messages table and this event message was interpreted as user message. Fix is here

https://github.com/buerokratt/Buerokratt-Chatbot/pull/844

**Comment by SanderSepp** [comment]
https://github.com/buerokratt/Buerokratt-Chatbot/pull/848
https://github.com/buerokratt/sample-implementation-cvi/pull/37

**Comment by jaX10bt** [comment]
Sound and pop-up notifications not working

**Comment by SanderSepp** [comment]
New chat notifications are working. One behavior could to be improved. Currently notifications are sent for each new customer message in any of the active chats (unanswered, active), IF there are any unanswered chats. Depending on business needs, the logic could be improved - whether to remove the unanswered chat length check to send notifications for all new messages regardless of the number of unanswered chats. OR if notification should be sent only about new chats (unanswered). Then we should not check for new messages in chats, instead we check only if there are any new chats.

Forwarded chat logic seems to be broken. Quick code assessment revealed that the business logic for sending notifications is there, but store state is in bad shape. Header and modules have separate stores. Header fetches and stores chats, messages etc, module is using header store for messages but stores user data in its own store. Therefore all the business checks related to user in header store are broken, because it does not contain user data. (Eg. idCode is used to find chat assignee (CSA))

**Comment by turnerrainer** [comment]
Will create a new issue based on what's left undone regarding this task.

**Comment by turnerrainer** [comment]
Close as taken over in https://github.com/buerokratt/Buerokratt-Chatbot/issues/878
